parameters:
  # Repo
  brander_eav.repo.value.class:
    Brander\Bundle\EAVBundle\Repo\Value
  brander_eav.repo.group.class:
    Doctrine\ORM\EntityRepository
  brander_eav.repo.set.class:
    Doctrine\ORM\EntityRepository
  brander_eav.repo.attribute.class:
    Brander\Bundle\EAVBundle\Repo\Attribute

services:
  # Repo
  brander_eav.repo.value:
    class:            "%brander_eav.repo.value.class%"
    factory:
      - "@doctrine.orm.entity_manager"
      - getRepository
    arguments: [BranderEAVBundle:Value]

  brander_eav.repo.attribute:
    class:            "%brander_eav.repo.attribute.class%"
    factory:
      - "@doctrine.orm.entity_manager"
      - getRepository
    arguments: [BranderEAVBundle:Attribute]

  brander_eav.repo.group:
    class:            "%brander_eav.repo.group.class%"
    factory:
      - "@doctrine.orm.entity_manager"
      - getRepository
    arguments: [BranderEAVBundle:AttributeGroup]

  brander_eav.repo.set:
    class:            "%brander_eav.repo.set.class%"
    factory:
      - "@doctrine.orm.entity_manager"
      - getRepository
    arguments: [BranderEAVBundle:AttributeSet]
