parameters:
  brander_eav.eventlistener.valueselectlistener.class: Brander\Bundle\EAVBundle\EventListener\ValueSelectListener
  brander_eav.attribute.holder.class: Brander\Bundle\EAVBundle\Service\Holder
  brander_eav.twig.extension.class: Brander\Bundle\EAVBundle\Service\Twig\BranderEAVExtension
  brander_eav.extensible_entity.handler.class: Brander\Bundle\EAVBundle\Service\Serialize\SerializeHandler
  brander_eav.security.universal_voter.class: Brander\Bundle\EAVBundle\Service\Security\UniversalManageVoter
  brander_eav.attribute.serialize.query_holder.class: Brander\Bundle\EAVBundle\Service\Serialize\QueryDeserializeHolder
  brander_eav.filter.holder.class: Brander\Bundle\EAVBundle\Service\Filter\FilterHolder
  brander_eav.filter.standard_models.class: Brander\Bundle\EAVBundle\Service\Filter\FilterProvider
  brander_eav.elastica.value_stats_provider.class: Brander\Bundle\EAVBundle\Service\Stats\ValueStatsProvider
  brander_eav.stats.stats_holder.class: Brander\Bundle\EAVBundle\Service\Stats\StatsHolder
  validator.eav_value.class: Brander\Bundle\EAVBundle\Validator\Constraint\EavConstraintValidation
  brander_eav.elastica.value_stats.default_life_time: 3600

services:
  brander_eav.eventlistener.valueselectlistener:
    class: "%brander_eav.eventlistener.valueselectlistener.class%"
    tags:
      - { name: doctrine.event_subscriber }

  brander_eav.twig.appextension:
    class: "%brander_eav.twig.extension.class%"
    public: false
    arguments:
      - "@doctrine.orm.entity_manager"
      - "%brander_eav.locales_supported%"
      - "%locale%"
    tags:
      - { name: twig.extension }

  brander_eav.attribute.holder:
    class: "%brander_eav.attribute.holder.class%"
    arguments:
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: jms_serializer.event_subscriber }

  brander_eav.attribute.serialize.query_holder:
    class: "%brander_eav.attribute.serialize.query_holder.class%"
    arguments:
      - "@brander_eav.repo.attribute"
      - "@brander_eav.stats.stats_holder" # "@cache.app" # TODO
    tags:
      - { name: jms_serializer.event_subscriber }

  brander_eav.extensible_entity.handler:
    class: "%brander_eav.extensible_entity.handler.class%"
    arguments:
     - {}
     - "@request_stack"
     - "@jms_serializer.event_dispatcher"
     - "%locale%"

  brander_eav.security.universal_voter:
    class: "%brander_eav.security.universal_voter.class%"
    arguments:
      - "%brander_eav.managerole%"
    tags:
      - { name: security.voter }

  brander_eav.filter.holder:
    arguments: {}
    class: "%brander_eav.filter.holder.class%"

  brander_eav.filter.provider.standard_models:
    arguments: {}
    class: "%brander_eav.filter.standard_models.class%"
    tags:
      - { name: brander_eav.filter.provider }

  brander_eav.elastica.value_stats_provider:
    class: "%brander_eav.elastica.value_stats_provider.class%"
    arguments:
      - "@brander_eav.repo.value"
    tags:
      - { name: brander_eav.stats.provider }

  brander_eav.stats.stats_holder:
    class: "%brander_eav.stats.stats_holder.class%"
    arguments:
      - "@cache.app"
      - "%brander_eav.elastica.value_stats.default_life_time%"

  product.filter.custom_filters_provider:
    class: Shatel\ProductBundle\Service\Filter\CustomFilterProvider
    tags:
      - { name: brander_eav.filter.provider }

  validator.eav_value:
    class: "%validator.eav_value.class%"
    arguments:
      - "%locale%"
      - "@request_stack"
    tags:
        - { name: validator.constraint_validator, alias: validator.eav_value}