parameters:
  brander_eav.eventlistener.valueselectlistener.class: Brander\Bundle\EAVBundle\EventListener\ValueSelectListener
  brander_eav.attribute.holder.class: Brander\Bundle\EAVBundle\Service\Holder
  brander_eav.twig.extension.class: Brander\Bundle\EAVBundle\Service\Twig\BranderEAVExtension
  brander_eav.extensible_entity.handler.class: Brander\Bundle\EAVBundle\Service\Serialize\SerializeHandler
  brander_eav.security.universal_voter.class: Brander\Bundle\EAVBundle\Service\Security\UniversalManageVoter
  brander_eav.attribute.serialize.query_holder.class: Brander\Bundle\EAVBundle\Service\Serialize\QueryDeserializeHolder
  brander_eav.filter.holder.class: Brander\Bundle\EAVBundle\Service\Filter\FilterHolder
  brander_eav.filter.standard_models.class: Brander\Bundle\EAVBundle\Service\Filter\FilterProvider
  brander_eav.elastica.value_stats_provider.class: Brander\Bundle\EAVBundle\Service\Elastica\ValueStatsProvider
  brander_eav.stats.stats_holder.class: Brander\Bundle\EAVBundle\Service\Filter\StatsHolder

services:
  brander_eav.eventlistener.valueselectlistener:
    class: "%brander_eav.eventlistener.valueselectlistener.class%"
    tags:
      - { name: doctrine.event_subscriber }

  brander_eav.twig.appextension:
    class: "%brander_eav.twig.extension.class%"
    public: false
    arguments:
      - "@doctrine.orm.entity_manager"
      - "%brander_eav.locales_supported%"
      - "%locale%"
    tags:
      - { name: twig.extension }

  brander_eav.attribute.holder:
    class: "%brander_eav.attribute.holder.class%"
    arguments:
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: jms_serializer.event_subscriber }

  brander_eav.attribute.serialize.query_holder:
    class: "%brander_eav.attribute.serialize.query_holder.class%"
    arguments:
      - "@brander_eav.repo.attribute"
      - "@cache.app" # TODO
    tags:
      - { name: jms_serializer.event_subscriber }

  brander_eav.extensible_entity.handler:
    arguments:
     - {}
     - "@service_container"
     - "%locale%"
    class: "%brander_eav.extensible_entity.handler.class%"

  brander_eav.security.universal_voter:
    class: "%brander_eav.security.universal_voter.class%"
    arguments:
      - "%brander_eav.managerole%"
    tags:
      - { name: security.voter }

  brander_eav.filter.holder:
    arguments: {}
    class: "%brander_eav.filter.holder.class%"

  brander_eav.filter.provider.standard_models:
    arguments: {}
    class: "%brander_eav.filter.standard_models.class%"
    tags:
      - { name: brander_eav.filter.provider }

  brander_eav.elastica.value_stats_provider:
    class: "%brander_eav.elastica.value_stats_provider.class%"
    arguments:
      - "@brander_eav.repo.value"
    tags:
      - { name: werkint_stats.provider }

  brander_eav.stats.stats_holder:
    class: "%brander_eav.stats.stats_holder.class%"
    arguments:
      - "@cache.app"
